name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        environment-file: environment.yml
        python-version: 3.9
        auto-activate-base: true
    - name: Install deepface
      run: |
        pip install deepface
    - name: Run emotion detection script
      run: |
        python emotions_Deepface.py
    - name: Run emotion recognition script
      run: |
        python emotions_recognition_Deepface.py
